# Site settings
title: patrick ahearn
email: patrick.ahearn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  mostly about data
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: PatrickAhearn1
github_username:  pahearn1

# Build settings
markdown: kramdown

highlighter: rogue

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
